pipeline {
    agent { label 'nodejs' }

    environment { APP_NAMESPACE = 'greeting-cd-pipeline' }

    stages{
        stage('Test'){
            steps {
                dir(APP_NAMESPACE) {
                  sh "node test.js"
                }
            }
        }

        // Add more stages here
        stage('Deploy') {
            steps {
                sh '''
                    oc start-build greeting-metrics \
                    --follow --wait -n patelgopal-metrics
                '''
            }
        }
    }
}
